
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-20T11:22:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5b5130c0f04ff4093c5b0a0d28ff691a7e3df53",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
